### PR TITLE
Fixes for the resumable downloads feature

### PR DESCRIPTION
**Pull request by EzioTheDeadPoet**
#2340 
by @UrbanCMC

### CODE REVIEW

**Comment by EzioTheDeadPoet** [comment]
A dev build of those fixes has been tested on the discord for a while now and caused no obvious issues.

**Comment by selsie** [comment]
finally. Not downloading 13GB files over and over...
Thanks for fixing it, when will it be implemented in the release version?

**Comment by EzioTheDeadPoet** [comment]
no ETA

**Comment by EzioTheDeadPoet** [comment]
@UrbanCMC I just looked at the code again, it looks like the revert of the maximum 8 thread count setting isn't here yet. So if you could make a PR for that to the branch I am using to merge this changes that would be amazing.

**Pull request merged**
