### PR TITLE
Deadlystream support

### PR DESCRIPTION
**Pull request by erri120**

### CODE REVIEW

**Comment by halgari** [comment]
You'll probably want to rework this against #353 once it gets merged.

**Comment by erri120** [comment]
Will redo this

**Comment by halgari** [comment]
@erri120 it looks like Deadlystream might also be a IPS4 site? If so look at the implementation of VectorPlexus as any IPS4 site should be implementable in about 20 lines of code

**Comment by erri120** [comment]
yeah just saw it

**Pull request closed without merging**
