### PR TITLE
Fix navigation through cloudflare

### LINKED ISSUE #1515: v2.5.0.3 Cannot login to LL through the client
**Describe the bug**

Currently logging in to the client on a fresh install of Wabbajack prompts the user to authorize use, with no context in the bullet point and hangs on a white screen after continuing with your account information.

**Additional Context**

Windows 10

**Wabbajack Version**

v2.5.0.3

**Logs**

```0.34 - Wabbajack Build - 10edda9bb51a164e64e97af543f6475a5c332d8f
0.35 - Running in E:\Wabbajack\2.5.0.3
0.36 - Detected Windows Version: 10.0.17763.0
0.36 - System settings - (31.9GB RAM) (2GB Page), Display: 2560 x 1440 (7.9GB VRAM - VideoMemorySizeMb=10240)
0.36 - Pagefile below recommended! Consider increasing to 20000MB. A suboptimal pagefile can cause crashes and poor in-game performance.
0.38 - Getting new Wabbajack version list

0.41 - Steam: Found game The Elder Scrolls V: Skyrim Special Edition (489830)

0.41 - Errors while finding Games from GOGHandler
GOG not found in registry!
0.42 - Errors while finding Games from BethNetHandler
Unable to open Registry Key SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net
0.42 - Configuring with SSL None
0.46 - Found MFSTs from Origin: 
0.93 - Wabbajack Version: 2.5.0.3
1.16 - Build server is alive
1.16 - File hash check (-42) 94aa4cb85e0f1d21564d858a7c5cf449796771d540215b54b5db8de26615f415
1.31 - Build server is alive
1.31 - File hash check (-42) 94aa4cb85e0f1d21564d858a7c5cf449796771d540215b54b5db8de26615f415
38.46 - Loading ModLists from GitHub
47.73 - Starting to install Licentia
47.74 - Cleaning VFS, this may take a bit of time
47.78 - Starting Installer Task
47.78 - Installation has Started
47.78 - File hash check (-42) 94aa4cb85e0f1d21564d858a7c5cf449796771d540215b54b5db8de26615f415
48.35 - Configuring Processor
48.36 - Install Folder: E:\SkyrimMods
48.36 - Downloads Folder: E:\SkyrimMods\download
48.36 - Game Folder: E:\SteamLibrary\steamapps\common\Skyrim Special Edition
48.36 - Wabbajack Folder: E:\Wabbajack\2.5.0.3
48.37 - Drive watcher is starting. Will warn at 8GB and error at 4GB
48.37 - Starting Drive watcher on E:\ currently 750.4GB free out of 931.5GB
48.37 - Validating Game ESMs
48.39 - Creating Output Folders
48.51 - Optimizing ModList
48.51 - Optimizing ModList directives
50.9 - Looking for files to delete
50.91 - Cleaning empty folders
51.87 - Looking for unmodified files
52.48 - Updating ModList
52.48 - Optimized 175774 directives to 175774 required
52.55 - Hashing Archives
52.55 - Looking for files to hash
52.67 - Found 918 total files, 17 matching filesize
52.71 - Downloading Missing Archives
52.71 - Missing 603 archives
52.71 - Getting Nexus API Key, if a browser appears, please accept
52.76 - Getting Lovers Lab Login
53.41 - Logged into the nexus as redacted
53.41 - Nexus calls remaining: 2500 daily, 100 hourly
395.53 - System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Wabbajack.Lib.Downloaders.AbstractIPS4OAuthDownloader`2.<GetAuthedClient>b__42_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\Downloaders\AbstractIPS4OAuthDownloader.cs:line 101
   at Wabbajack.Common.Utils.CatchAndLog(Func`1 f) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Common\Logging.cs:line 163
395.53 - System.Exception: Must log into Lovers Lab to continue
395.53 - File hash check (-42) 94aa4cb85e0f1d21564d858a7c5cf449796771d540215b54b5db8de26615f415
395.61 - Encountered error, can't continue - System.Exception: Must log into Lovers Lab to continue
   at Wabbajack.Common.Utils.ErrorThrow(Exception ex, String extraMessage) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Common\Logging.cs:line 109
   at Wabbajack.Lib.Downloaders.AbstractIPS4OAuthDownloader`2.GetAuthedClient() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\Downloaders\AbstractIPS4OAuthDownloader.cs:line 104
   at Wabbajack.Lib.Downloaders.AbstractIPS4OAuthDownloader`2.Prepare() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\Downloaders\AbstractIPS4OAuthDownloader.cs:line 92
   at Wabbajack.Lib.AInstaller.DownloadArchives() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 214
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 138
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
395.92 - File hash check (-42) 94aa4cb85e0f1d21564d858a7c5cf449796771d540215b54b5db8de26615f415
400.67 - Getting Lovers Lab Login

### PR DESCRIPTION
**Pull request by MokhamedDakhraui**
PR fixes:
- Problem called white screen of death, which is caused by unsuccessfull attempt to authorize in sites with oauth
- 503 status code on downloading mods from sites with oauth
- Other obstacles on my way here (described further in commit messages)

fixes #1515 #1523

### CODE REVIEW

**Comment by MokhamedDakhraui** [comment]
@halgari, seems approval timeout prevented execution of build

**Comment by MokhamedDakhraui** [comment]
@halgari ping?

**Comment by halgari** [comment]
About a month ago I started a rewrite of the app to .NET 6, and in the process did a major refactoring of all this code (see https://github.com/wabbajack-tools/wabbajack-redux) part of that work involved tracking down a lot of these issues and making the entire system much more modular. Feel free to ping me on the discord (https://discord.gg/wabbajack) and we can figure out how to get some of these changes in and get you up and running with the new codebase. But for now the 2.5 version of wabbajack is in maintenance mode. Until I get 3.0 out.

**Comment by MokhamedDakhraui** [comment]
Understood. Then, I guess, there is no need in this PR for now. I'll make new fix if I stumble upon the problem in stable 3.0 (redux) version. For now will rebase this changes for myself locally

**Pull request closed without merging**
