### PR TITLE
Improve game selection in the modlist gallery

### PR DESCRIPTION
**Pull request by tr4wzified**
mkQZzPXjtL
- Only games that have modlists are shown now
- Amount of lists for a game is shown
- Now able to filter for game in combination with filtering on only installed modlists

### CODE REVIEW

**Comment by EzioTheDeadPoet** [comment]
if you change the branch to merge onto to https://github.com/wabbajack-tools/wabbajack/tree/main_test_external_pull I can merge it and we should get the proper tests run on #2325

**Comment by tr4wzified** [comment]
Cool will do, @EzioTheDeadPoet

**Comment by EzioTheDeadPoet** [comment]
@tr4wzified I changed the branch here but you might need to update the conflict. and ideally add your changes to the CHANGELOG.md file :D

**Comment by tr4wzified** [comment]
Thanks, saw you got it already, I'll base future changes on the other branch :)

**Pull request merged**
