### PR TITLE
adds option to include save files if wanted.

### LINKED ISSUE #1356: Ability to set a tag to skip the "skipping" of savefiles
**Is your feature request related to a problem? Please describe.**

Some people want to include preset saves for their lists.

**Describe the solution you'd like**

A tag-file in the root folder that forces the list compiler to skip the step intended to exclude the save files, so the save files get included.

**Describe alternatives you've considered**

just uploading them somewhere.

**Additional context**

mostly a note for me so I don't forget to do this eventually.

### PR DESCRIPTION
**Pull request by EzioTheDeadPoet**
- Closes  #1356 
Mainly to allow a different form of MCM automation.

### CODE REVIEW

**Comment by erri120** [comment]
I think it would be better to just change https://github.com/wabbajack-tools/wabbajack/blob/master/Wabbajack.Lib/CompilationSteps/IgnoreSaveFiles.cs

**Comment by EzioTheDeadPoet** [comment]
fair point

**Comment by EzioTheDeadPoet** [comment]
Doing a local test rn of an adjusted version.
Any clue why the master is failing and therefore my PRs based on it ? 
Cause GitHub says that the build while it builds just fine locally.

**Comment by erri120** [comment]
> 
> 
> Doing a local test rn of an adjusted version.
> Any clue why the master is failing and therefore my PRs based on it ?
> Cause GitHub says that the build while it builds just fine locally.

some tests fail

**Comment by EzioTheDeadPoet** [comment]
So compile with the "tagfile" set and install worked. testing without it now.

**Comment by EzioTheDeadPoet** [comment]
Only merge shortly before release, since I added the instructions for this to the `README.md`

**Pull request merged**
